builds:
- id: kyverno-runtime
  dir: ./cmd/kyverno-runtime
  env:
    - CGO_ENABLED=0
  main: .

baseImageOverrides:
  github.com/nirmata/kyverno-runtime/cmd/kyverno-runtime: gcr.io/distroless/base-debian12:nonroot

defaultBaseImage: gcr.io/distroless/base-debian12:nonroot
