// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package egressfilter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type egressBlockDomainKey struct {
	_    structs.HostLayout
	Name [128]uint8
}

type egressBlockIpEventKey struct {
	_        structs.HostLayout
	Daddr    uint32
	Decision uint32
	DomainId uint32
}

// loadEgressBlock returns the embedded CollectionSpec for egressBlock.
func loadEgressBlock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EgressBlockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load egressBlock: %w", err)
	}

	return spec, err
}

// loadEgressBlockObjects loads egressBlock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*egressBlockObjects
//	*egressBlockPrograms
//	*egressBlockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEgressBlockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEgressBlock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// egressBlockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockSpecs struct {
	egressBlockProgramSpecs
	egressBlockMapSpecs
	egressBlockVariableSpecs
}

// egressBlockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockProgramSpecs struct {
	CgroupDnsIngress *ebpf.ProgramSpec `ebpf:"cgroup_dns_ingress"`
	CgroupEgress     *ebpf.ProgramSpec `ebpf:"cgroup_egress"`
}

// egressBlockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockMapSpecs struct {
	AllowedDomains *ebpf.MapSpec `ebpf:"allowed_domains"`
	AllowedIps     *ebpf.MapSpec `ebpf:"allowed_ips"`
	BannedDomains  *ebpf.MapSpec `ebpf:"banned_domains"`
	BannedIps      *ebpf.MapSpec `ebpf:"banned_ips"`
	DomainIds      *ebpf.MapSpec `ebpf:"domain_ids"`
	Flags          *ebpf.MapSpec `ebpf:"flags"`
	IpDomain       *ebpf.MapSpec `ebpf:"ip_domain"`
	IpEvents       *ebpf.MapSpec `ebpf:"ip_events"`
	Stats          *ebpf.MapSpec `ebpf:"stats"`
}

// egressBlockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockVariableSpecs struct {
}

// egressBlockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockObjects struct {
	egressBlockPrograms
	egressBlockMaps
	egressBlockVariables
}

func (o *egressBlockObjects) Close() error {
	return _EgressBlockClose(
		&o.egressBlockPrograms,
		&o.egressBlockMaps,
	)
}

// egressBlockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockMaps struct {
	AllowedDomains *ebpf.Map `ebpf:"allowed_domains"`
	AllowedIps     *ebpf.Map `ebpf:"allowed_ips"`
	BannedDomains  *ebpf.Map `ebpf:"banned_domains"`
	BannedIps      *ebpf.Map `ebpf:"banned_ips"`
	DomainIds      *ebpf.Map `ebpf:"domain_ids"`
	Flags          *ebpf.Map `ebpf:"flags"`
	IpDomain       *ebpf.Map `ebpf:"ip_domain"`
	IpEvents       *ebpf.Map `ebpf:"ip_events"`
	Stats          *ebpf.Map `ebpf:"stats"`
}

func (m *egressBlockMaps) Close() error {
	return _EgressBlockClose(
		m.AllowedDomains,
		m.AllowedIps,
		m.BannedDomains,
		m.BannedIps,
		m.DomainIds,
		m.Flags,
		m.IpDomain,
		m.IpEvents,
		m.Stats,
	)
}

// egressBlockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockVariables struct {
}

// egressBlockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockPrograms struct {
	CgroupDnsIngress *ebpf.Program `ebpf:"cgroup_dns_ingress"`
	CgroupEgress     *ebpf.Program `ebpf:"cgroup_egress"`
}

func (p *egressBlockPrograms) Close() error {
	return _EgressBlockClose(
		p.CgroupDnsIngress,
		p.CgroupEgress,
	)
}

func _EgressBlockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed egressblock_bpfeb.o
var _EgressBlockBytes []byte
