// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/learning.proto

package learning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BehaviorKind int32

const (
	BehaviorKind_BEHAVIOR_NETWORK BehaviorKind = 0
	BehaviorKind_BEHAVIOR_OPEN    BehaviorKind = 1
	BehaviorKind_BEHAVIOR_EXEC    BehaviorKind = 2
)

// Enum value maps for BehaviorKind.
var (
	BehaviorKind_name = map[int32]string{
		0: "BEHAVIOR_NETWORK",
		1: "BEHAVIOR_OPEN",
		2: "BEHAVIOR_EXEC",
	}
	BehaviorKind_value = map[string]int32{
		"BEHAVIOR_NETWORK": 0,
		"BEHAVIOR_OPEN":    1,
		"BEHAVIOR_EXEC":    2,
	}
)

func (x BehaviorKind) Enum() *BehaviorKind {
	p := new(BehaviorKind)
	*p = x
	return p
}

func (x BehaviorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BehaviorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_learning_proto_enumTypes[0].Descriptor()
}

func (BehaviorKind) Type() protoreflect.EnumType {
	return &file_proto_learning_proto_enumTypes[0]
}

func (x BehaviorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BehaviorKind.Descriptor instead.
func (BehaviorKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *StartRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StartRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{1}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{3}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	BehaviorKind  []BehaviorKind         `protobuf:"varint,2,rep,packed,name=behavior_kind,json=behaviorKind,proto3,enum=learning.BehaviorKind" json:"behavior_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReadRequest) GetBehaviorKind() []BehaviorKind {
	if x != nil {
		return x.BehaviorKind
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       map[uint32]uint32      `protobuf:"bytes,1,rep,name=network,proto3" json:"network,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Open          map[string]uint32      `protobuf:"bytes,2,rep,name=open,proto3" json:"open,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Exec          map[string]uint32      `protobuf:"bytes,3,rep,name=exec,proto3" json:"exec,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_learning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetNetwork() map[uint32]uint32 {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ReadResponse) GetOpen() map[string]uint32 {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *ReadResponse) GetExec() map[string]uint32 {
	if x != nil {
		return x.Exec
	}
	return nil
}

var File_proto_learning_proto protoreflect.FileDescriptor

const file_proto_learning_proto_rawDesc = "" +
	"\n" +
	"\x14proto/learning.proto\x12\blearning\x1a\x1egoogle/protobuf/duration.proto\"\xce\x01\n" +
	"\fStartRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12:\n" +
	"\x06labels\x18\x02 \x03(\v2\".learning.StartRequest.LabelsEntryR\x06labels\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rStartResponse\"\x1f\n" +
	"\vStopRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\x0e\n" +
	"\fStopResponse\"\\\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12;\n" +
	"\rbehavior_kind\x18\x02 \x03(\x0e2\x16.learning.BehaviorKindR\fbehaviorKind\"\xe7\x02\n" +
	"\fReadResponse\x12=\n" +
	"\anetwork\x18\x01 \x03(\v2#.learning.ReadResponse.NetworkEntryR\anetwork\x124\n" +
	"\x04open\x18\x02 \x03(\v2 .learning.ReadResponse.OpenEntryR\x04open\x124\n" +
	"\x04exec\x18\x03 \x03(\v2 .learning.ReadResponse.ExecEntryR\x04exec\x1a:\n" +
	"\fNetworkEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a7\n" +
	"\tOpenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a7\n" +
	"\tExecEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01*J\n" +
	"\fBehaviorKind\x12\x14\n" +
	"\x10BEHAVIOR_NETWORK\x10\x00\x12\x11\n" +
	"\rBEHAVIOR_OPEN\x10\x01\x12\x11\n" +
	"\rBEHAVIOR_EXEC\x10\x022\xb9\x01\n" +
	"\x0fLearningService\x128\n" +
	"\x05Start\x12\x16.learning.StartRequest\x1a\x17.learning.StartResponse\x125\n" +
	"\x04Stop\x12\x15.learning.StopRequest\x1a\x16.learning.StopResponse\x125\n" +
	"\x04Read\x12\x15.learning.ReadRequest\x1a\x16.learning.ReadResponseB7Z5github.com/nirmata/kyverno-runtime/pkg/proto/learningb\x06proto3"

var (
	file_proto_learning_proto_rawDescOnce sync.Once
	file_proto_learning_proto_rawDescData []byte
)

func file_proto_learning_proto_rawDescGZIP() []byte {
	file_proto_learning_proto_rawDescOnce.Do(func() {
		file_proto_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_learning_proto_rawDesc), len(file_proto_learning_proto_rawDesc)))
	})
	return file_proto_learning_proto_rawDescData
}

var file_proto_learning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_learning_proto_goTypes = []any{
	(BehaviorKind)(0),           // 0: learning.BehaviorKind
	(*StartRequest)(nil),        // 1: learning.StartRequest
	(*StartResponse)(nil),       // 2: learning.StartResponse
	(*StopRequest)(nil),         // 3: learning.StopRequest
	(*StopResponse)(nil),        // 4: learning.StopResponse
	(*ReadRequest)(nil),         // 5: learning.ReadRequest
	(*ReadResponse)(nil),        // 6: learning.ReadResponse
	nil,                         // 7: learning.StartRequest.LabelsEntry
	nil,                         // 8: learning.ReadResponse.NetworkEntry
	nil,                         // 9: learning.ReadResponse.OpenEntry
	nil,                         // 10: learning.ReadResponse.ExecEntry
	(*durationpb.Duration)(nil), // 11: google.protobuf.Duration
}
var file_proto_learning_proto_depIdxs = []int32{
	7,  // 0: learning.StartRequest.labels:type_name -> learning.StartRequest.LabelsEntry
	11, // 1: learning.StartRequest.duration:type_name -> google.protobuf.Duration
	0,  // 2: learning.ReadRequest.behavior_kind:type_name -> learning.BehaviorKind
	8,  // 3: learning.ReadResponse.network:type_name -> learning.ReadResponse.NetworkEntry
	9,  // 4: learning.ReadResponse.open:type_name -> learning.ReadResponse.OpenEntry
	10, // 5: learning.ReadResponse.exec:type_name -> learning.ReadResponse.ExecEntry
	1,  // 6: learning.LearningService.Start:input_type -> learning.StartRequest
	3,  // 7: learning.LearningService.Stop:input_type -> learning.StopRequest
	5,  // 8: learning.LearningService.Read:input_type -> learning.ReadRequest
	2,  // 9: learning.LearningService.Start:output_type -> learning.StartResponse
	4,  // 10: learning.LearningService.Stop:output_type -> learning.StopResponse
	6,  // 11: learning.LearningService.Read:output_type -> learning.ReadResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_learning_proto_init() }
func file_proto_learning_proto_init() {
	if File_proto_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_learning_proto_rawDesc), len(file_proto_learning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_learning_proto_goTypes,
		DependencyIndexes: file_proto_learning_proto_depIdxs,
		EnumInfos:         file_proto_learning_proto_enumTypes,
		MessageInfos:      file_proto_learning_proto_msgTypes,
	}.Build()
	File_proto_learning_proto = out.File
	file_proto_learning_proto_goTypes = nil
	file_proto_learning_proto_depIdxs = nil
}
