// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package dnsquery

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDnsQuery returns the embedded CollectionSpec for dnsQuery.
func loadDnsQuery() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsQueryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsQuery: %w", err)
	}

	return spec, err
}

// loadDnsQueryObjects loads dnsQuery and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsQueryObjects
//	*dnsQueryPrograms
//	*dnsQueryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsQueryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsQuery()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsQuerySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsQuerySpecs struct {
	dnsQueryProgramSpecs
	dnsQueryMapSpecs
	dnsQueryVariableSpecs
}

// dnsQueryProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsQueryProgramSpecs struct {
	CgroupDnsEgress *ebpf.ProgramSpec `ebpf:"cgroup_dns_egress"`
}

// dnsQueryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsQueryMapSpecs struct {
	Cgids  *ebpf.MapSpec `ebpf:"cgids"`
	Events *ebpf.MapSpec `ebpf:"events"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
}

// dnsQueryVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsQueryVariableSpecs struct {
}

// dnsQueryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsQueryObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsQueryObjects struct {
	dnsQueryPrograms
	dnsQueryMaps
	dnsQueryVariables
}

func (o *dnsQueryObjects) Close() error {
	return _DnsQueryClose(
		&o.dnsQueryPrograms,
		&o.dnsQueryMaps,
	)
}

// dnsQueryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsQueryObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsQueryMaps struct {
	Cgids  *ebpf.Map `ebpf:"cgids"`
	Events *ebpf.Map `ebpf:"events"`
	Stats  *ebpf.Map `ebpf:"stats"`
}

func (m *dnsQueryMaps) Close() error {
	return _DnsQueryClose(
		m.Cgids,
		m.Events,
		m.Stats,
	)
}

// dnsQueryVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsQueryObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsQueryVariables struct {
}

// dnsQueryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsQueryObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsQueryPrograms struct {
	CgroupDnsEgress *ebpf.Program `ebpf:"cgroup_dns_egress"`
}

func (p *dnsQueryPrograms) Close() error {
	return _DnsQueryClose(
		p.CgroupDnsEgress,
	)
}

func _DnsQueryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsquery_bpfeb.o
var _DnsQueryBytes []byte
