// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmDispatcherFileOpenLsmCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	Path         [128]int8
}

type lsmDispatcherFileOpenPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	lsmDispatcherFileOpenMapAllowed            = "allowed"
	lsmDispatcherFileOpenMapBanned             = "banned"
	lsmDispatcherFileOpenMapCgids              = "cgids"
	lsmDispatcherFileOpenMapCtxMap             = "ctx_map"
	lsmDispatcherFileOpenMapDefaultDeny        = "default_deny"
	lsmDispatcherFileOpenMapExecProgs          = "exec_progs"
	lsmDispatcherFileOpenMapInnerOpenEvents    = "inner_open_events"
	lsmDispatcherFileOpenMapOpenEvents         = "open_events"
	lsmDispatcherFileOpenMapOpenProgs          = "open_progs"
	lsmDispatcherFileOpenMapProgCount          = "prog_count"
	lsmDispatcherFileOpenMapStats              = "stats"
	lsmDispatcherFileOpenProgGenericLsmHandler = "generic_lsm_handler"
)

// loadLsmDispatcherFileOpen returns the embedded CollectionSpec for lsmDispatcherFileOpen.
func loadLsmDispatcherFileOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmDispatcherFileOpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmDispatcherFileOpen: %w", err)
	}

	return spec, err
}

// loadLsmDispatcherFileOpenObjects loads lsmDispatcherFileOpen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmDispatcherFileOpenObjects
//	*lsmDispatcherFileOpenPrograms
//	*lsmDispatcherFileOpenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmDispatcherFileOpenObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmDispatcherFileOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmDispatcherFileOpenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenSpecs struct {
	lsmDispatcherFileOpenProgramSpecs
	lsmDispatcherFileOpenMapSpecs
	lsmDispatcherFileOpenVariableSpecs
}

// lsmDispatcherFileOpenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmDispatcherFileOpenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// lsmDispatcherFileOpenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenVariableSpecs struct {
}

// lsmDispatcherFileOpenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenObjects struct {
	lsmDispatcherFileOpenPrograms
	lsmDispatcherFileOpenMaps
	lsmDispatcherFileOpenVariables
}

func (o *lsmDispatcherFileOpenObjects) Close() error {
	return _LsmDispatcherFileOpenClose(
		&o.lsmDispatcherFileOpenPrograms,
		&o.lsmDispatcherFileOpenMaps,
	)
}

// lsmDispatcherFileOpenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *lsmDispatcherFileOpenMaps) Close() error {
	return _LsmDispatcherFileOpenClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// lsmDispatcherFileOpenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenVariables struct {
}

// lsmDispatcherFileOpenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmDispatcherFileOpenPrograms) Close() error {
	return _LsmDispatcherFileOpenClose(
		p.GenericLsmHandler,
	)
}

func _LsmDispatcherFileOpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmdispatcherfileopen_bpfeb.o
var _LsmDispatcherFileOpenBytes []byte
