// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmDispatcherExecCheckLsmCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	Path         [128]int8
}

type lsmDispatcherExecCheckPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	lsmDispatcherExecCheckMapAllowed            = "allowed"
	lsmDispatcherExecCheckMapBanned             = "banned"
	lsmDispatcherExecCheckMapCgids              = "cgids"
	lsmDispatcherExecCheckMapCtxMap             = "ctx_map"
	lsmDispatcherExecCheckMapDefaultDeny        = "default_deny"
	lsmDispatcherExecCheckMapExecProgs          = "exec_progs"
	lsmDispatcherExecCheckMapInnerOpenEvents    = "inner_open_events"
	lsmDispatcherExecCheckMapOpenEvents         = "open_events"
	lsmDispatcherExecCheckMapOpenProgs          = "open_progs"
	lsmDispatcherExecCheckMapProgCount          = "prog_count"
	lsmDispatcherExecCheckMapStats              = "stats"
	lsmDispatcherExecCheckProgGenericLsmHandler = "generic_lsm_handler"
)

// loadLsmDispatcherExecCheck returns the embedded CollectionSpec for lsmDispatcherExecCheck.
func loadLsmDispatcherExecCheck() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmDispatcherExecCheckBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmDispatcherExecCheck: %w", err)
	}

	return spec, err
}

// loadLsmDispatcherExecCheckObjects loads lsmDispatcherExecCheck and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmDispatcherExecCheckObjects
//	*lsmDispatcherExecCheckPrograms
//	*lsmDispatcherExecCheckMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmDispatcherExecCheckObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmDispatcherExecCheck()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmDispatcherExecCheckSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherExecCheckSpecs struct {
	lsmDispatcherExecCheckProgramSpecs
	lsmDispatcherExecCheckMapSpecs
	lsmDispatcherExecCheckVariableSpecs
}

// lsmDispatcherExecCheckProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherExecCheckProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmDispatcherExecCheckMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherExecCheckMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// lsmDispatcherExecCheckVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherExecCheckVariableSpecs struct {
}

// lsmDispatcherExecCheckObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherExecCheckObjects struct {
	lsmDispatcherExecCheckPrograms
	lsmDispatcherExecCheckMaps
	lsmDispatcherExecCheckVariables
}

func (o *lsmDispatcherExecCheckObjects) Close() error {
	return _LsmDispatcherExecCheckClose(
		&o.lsmDispatcherExecCheckPrograms,
		&o.lsmDispatcherExecCheckMaps,
	)
}

// lsmDispatcherExecCheckMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherExecCheckMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *lsmDispatcherExecCheckMaps) Close() error {
	return _LsmDispatcherExecCheckClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// lsmDispatcherExecCheckVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherExecCheckVariables struct {
}

// lsmDispatcherExecCheckPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherExecCheckPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmDispatcherExecCheckPrograms) Close() error {
	return _LsmDispatcherExecCheckClose(
		p.GenericLsmHandler,
	)
}

func _LsmDispatcherExecCheckClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmdispatcherexeccheck_bpfel.o
var _LsmDispatcherExecCheckBytes []byte
