// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmExecCheckPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// loadLsmExecCheck returns the embedded CollectionSpec for lsmExecCheck.
func loadLsmExecCheck() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmExecCheckBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmExecCheck: %w", err)
	}

	return spec, err
}

// loadLsmExecCheckObjects loads lsmExecCheck and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmExecCheckObjects
//	*lsmExecCheckPrograms
//	*lsmExecCheckMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmExecCheckObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmExecCheck()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmExecCheckSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmExecCheckSpecs struct {
	lsmExecCheckProgramSpecs
	lsmExecCheckMapSpecs
	lsmExecCheckVariableSpecs
}

// lsmExecCheckProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmExecCheckProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmExecCheckMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmExecCheckMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// lsmExecCheckVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmExecCheckVariableSpecs struct {
}

// lsmExecCheckObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmExecCheckObjects struct {
	lsmExecCheckPrograms
	lsmExecCheckMaps
	lsmExecCheckVariables
}

func (o *lsmExecCheckObjects) Close() error {
	return _LsmExecCheckClose(
		&o.lsmExecCheckPrograms,
		&o.lsmExecCheckMaps,
	)
}

// lsmExecCheckMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmExecCheckMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *lsmExecCheckMaps) Close() error {
	return _LsmExecCheckClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.DefaultDeny,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.Stats,
	)
}

// lsmExecCheckVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmExecCheckVariables struct {
}

// lsmExecCheckPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmExecCheckPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmExecCheckPrograms) Close() error {
	return _LsmExecCheckClose(
		p.GenericLsmHandler,
	)
}

func _LsmExecCheckClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmexeccheck_bpfeb.o
var _LsmExecCheckBytes []byte
