// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadLsmFileOpen returns the embedded CollectionSpec for lsmFileOpen.
func loadLsmFileOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmFileOpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmFileOpen: %w", err)
	}

	return spec, err
}

// loadLsmFileOpenObjects loads lsmFileOpen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmFileOpenObjects
//	*lsmFileOpenPrograms
//	*lsmFileOpenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmFileOpenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmFileOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmFileOpenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmFileOpenSpecs struct {
	lsmFileOpenProgramSpecs
	lsmFileOpenMapSpecs
	lsmFileOpenVariableSpecs
}

// lsmFileOpenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmFileOpenProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmFileOpenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmFileOpenMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
}

// lsmFileOpenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmFileOpenVariableSpecs struct {
}

// lsmFileOpenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmFileOpenObjects struct {
	lsmFileOpenPrograms
	lsmFileOpenMaps
	lsmFileOpenVariables
}

func (o *lsmFileOpenObjects) Close() error {
	return _LsmFileOpenClose(
		&o.lsmFileOpenPrograms,
		&o.lsmFileOpenMaps,
	)
}

// lsmFileOpenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmFileOpenMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
}

func (m *lsmFileOpenMaps) Close() error {
	return _LsmFileOpenClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.DefaultDeny,
		m.InnerOpenEvents,
		m.OpenEvents,
	)
}

// lsmFileOpenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmFileOpenVariables struct {
}

// lsmFileOpenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmFileOpenPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmFileOpenPrograms) Close() error {
	return _LsmFileOpenClose(
		p.GenericLsmHandler,
	)
}

func _LsmFileOpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmfileopen_bpfel.o
var _LsmFileOpenBytes []byte
