// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadLsmGeneric returns the embedded CollectionSpec for lsmGeneric.
func loadLsmGeneric() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmGenericBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmGeneric: %w", err)
	}

	return spec, err
}

// loadLsmGenericObjects loads lsmGeneric and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmGenericObjects
//	*lsmGenericPrograms
//	*lsmGenericMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmGenericObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmGeneric()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmGenericSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmGenericSpecs struct {
	lsmGenericProgramSpecs
	lsmGenericMapSpecs
	lsmGenericVariableSpecs
}

// lsmGenericProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmGenericProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmGenericMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmGenericMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Argtypes        *ebpf.MapSpec `ebpf:"argtypes"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
}

// lsmGenericVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmGenericVariableSpecs struct {
}

// lsmGenericObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmGenericObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmGenericObjects struct {
	lsmGenericPrograms
	lsmGenericMaps
	lsmGenericVariables
}

func (o *lsmGenericObjects) Close() error {
	return _LsmGenericClose(
		&o.lsmGenericPrograms,
		&o.lsmGenericMaps,
	)
}

// lsmGenericMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmGenericObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmGenericMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Argtypes        *ebpf.Map `ebpf:"argtypes"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
}

func (m *lsmGenericMaps) Close() error {
	return _LsmGenericClose(
		m.Allowed,
		m.Argtypes,
		m.Banned,
		m.Cgids,
		m.DefaultDeny,
		m.InnerOpenEvents,
		m.OpenEvents,
	)
}

// lsmGenericVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmGenericObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmGenericVariables struct {
}

// lsmGenericPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmGenericObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmGenericPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmGenericPrograms) Close() error {
	return _LsmGenericClose(
		p.GenericLsmHandler,
	)
}

func _LsmGenericClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmgeneric_bpfel.o
var _LsmGenericBytes []byte
