// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmRuntimePolicyLsmCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	Path         [128]int8
}

type lsmRuntimePolicyPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	lsmRuntimePolicyMapAllowed                = "allowed"
	lsmRuntimePolicyMapBanned                 = "banned"
	lsmRuntimePolicyMapCgids                  = "cgids"
	lsmRuntimePolicyMapChainProgs             = "chain_progs"
	lsmRuntimePolicyMapCtxMap                 = "ctx_map"
	lsmRuntimePolicyMapDefaultDeny            = "default_deny"
	lsmRuntimePolicyMapExecProgs              = "exec_progs"
	lsmRuntimePolicyMapInnerOpenEvents        = "inner_open_events"
	lsmRuntimePolicyMapOpenEvents             = "open_events"
	lsmRuntimePolicyMapOpenProgs              = "open_progs"
	lsmRuntimePolicyMapProgCount              = "prog_count"
	lsmRuntimePolicyMapStats                  = "stats"
	lsmRuntimePolicyProgRuntimePolicyExecutor = "runtime_policy_executor"
)

// loadLsmRuntimePolicy returns the embedded CollectionSpec for lsmRuntimePolicy.
func loadLsmRuntimePolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmRuntimePolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmRuntimePolicy: %w", err)
	}

	return spec, err
}

// loadLsmRuntimePolicyObjects loads lsmRuntimePolicy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmRuntimePolicyObjects
//	*lsmRuntimePolicyPrograms
//	*lsmRuntimePolicyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmRuntimePolicyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmRuntimePolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmRuntimePolicySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmRuntimePolicySpecs struct {
	lsmRuntimePolicyProgramSpecs
	lsmRuntimePolicyMapSpecs
	lsmRuntimePolicyVariableSpecs
}

// lsmRuntimePolicyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmRuntimePolicyProgramSpecs struct {
	RuntimePolicyExecutor *ebpf.ProgramSpec `ebpf:"runtime_policy_executor"`
}

// lsmRuntimePolicyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmRuntimePolicyMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	ChainProgs      *ebpf.MapSpec `ebpf:"chain_progs"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// lsmRuntimePolicyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmRuntimePolicyVariableSpecs struct {
}

// lsmRuntimePolicyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmRuntimePolicyObjects struct {
	lsmRuntimePolicyPrograms
	lsmRuntimePolicyMaps
	lsmRuntimePolicyVariables
}

func (o *lsmRuntimePolicyObjects) Close() error {
	return _LsmRuntimePolicyClose(
		&o.lsmRuntimePolicyPrograms,
		&o.lsmRuntimePolicyMaps,
	)
}

// lsmRuntimePolicyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmRuntimePolicyMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	ChainProgs      *ebpf.Map `ebpf:"chain_progs"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *lsmRuntimePolicyMaps) Close() error {
	return _LsmRuntimePolicyClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.ChainProgs,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// lsmRuntimePolicyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmRuntimePolicyVariables struct {
}

// lsmRuntimePolicyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmRuntimePolicyPrograms struct {
	RuntimePolicyExecutor *ebpf.Program `ebpf:"runtime_policy_executor"`
}

func (p *lsmRuntimePolicyPrograms) Close() error {
	return _LsmRuntimePolicyClose(
		p.RuntimePolicyExecutor,
	)
}

func _LsmRuntimePolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmruntimepolicy_bpfeb.o
var _LsmRuntimePolicyBytes []byte
