// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadEgressBlock returns the embedded CollectionSpec for egressBlock.
func loadEgressBlock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EgressBlockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load egressBlock: %w", err)
	}

	return spec, err
}

// loadEgressBlockObjects loads egressBlock and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*egressBlockObjects
//	*egressBlockPrograms
//	*egressBlockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEgressBlockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEgressBlock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// egressBlockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockSpecs struct {
	egressBlockProgramSpecs
	egressBlockMapSpecs
	egressBlockVariableSpecs
}

// egressBlockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockProgramSpecs struct {
	TcEgress *ebpf.ProgramSpec `ebpf:"tc_egress"`
}

// egressBlockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockMapSpecs struct {
	BannedIps1 *ebpf.MapSpec `ebpf:"banned_ips_1"`
}

// egressBlockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressBlockVariableSpecs struct {
}

// egressBlockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockObjects struct {
	egressBlockPrograms
	egressBlockMaps
	egressBlockVariables
}

func (o *egressBlockObjects) Close() error {
	return _EgressBlockClose(
		&o.egressBlockPrograms,
		&o.egressBlockMaps,
	)
}

// egressBlockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockMaps struct {
	BannedIps1 *ebpf.Map `ebpf:"banned_ips_1"`
}

func (m *egressBlockMaps) Close() error {
	return _EgressBlockClose(
		m.BannedIps1,
	)
}

// egressBlockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockVariables struct {
}

// egressBlockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEgressBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressBlockPrograms struct {
	TcEgress *ebpf.Program `ebpf:"tc_egress"`
}

func (p *egressBlockPrograms) Close() error {
	return _EgressBlockClose(
		p.TcEgress,
	)
}

func _EgressBlockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed egressblock_bpfel.o
var _EgressBlockBytes []byte
