/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/nirmata/kyverno-runtime/api/v1alpha1"
	scheme "github.com/nirmata/kyverno-runtime/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AIInventoriesGetter has a method to return a AIInventoryInterface.
// A group's client should implement this interface.
type AIInventoriesGetter interface {
	AIInventories() AIInventoryInterface
}

// AIInventoryInterface has methods to work with AIInventory resources.
type AIInventoryInterface interface {
	Create(ctx context.Context, aIInventory *apiv1alpha1.AIInventory, opts v1.CreateOptions) (*apiv1alpha1.AIInventory, error)
	Update(ctx context.Context, aIInventory *apiv1alpha1.AIInventory, opts v1.UpdateOptions) (*apiv1alpha1.AIInventory, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aIInventory *apiv1alpha1.AIInventory, opts v1.UpdateOptions) (*apiv1alpha1.AIInventory, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.AIInventory, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.AIInventoryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.AIInventory, err error)
	AIInventoryExpansion
}

// aIInventories implements AIInventoryInterface
type aIInventories struct {
	*gentype.ClientWithList[*apiv1alpha1.AIInventory, *apiv1alpha1.AIInventoryList]
}

// newAIInventories returns a AIInventories
func newAIInventories(c *RuntimeV1alpha1Client) *aIInventories {
	return &aIInventories{
		gentype.NewClientWithList[*apiv1alpha1.AIInventory, *apiv1alpha1.AIInventoryList](
			"aiinventories",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.AIInventory { return &apiv1alpha1.AIInventory{} },
			func() *apiv1alpha1.AIInventoryList { return &apiv1alpha1.AIInventoryList{} },
		),
	}
}
