/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/nirmata/kyverno-runtime/api/v1alpha1"
	scheme "github.com/nirmata/kyverno-runtime/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RuntimeBehaviorsGetter has a method to return a RuntimeBehaviorInterface.
// A group's client should implement this interface.
type RuntimeBehaviorsGetter interface {
	RuntimeBehaviors(namespace string) RuntimeBehaviorInterface
}

// RuntimeBehaviorInterface has methods to work with RuntimeBehavior resources.
type RuntimeBehaviorInterface interface {
	Create(ctx context.Context, runtimeBehavior *apiv1alpha1.RuntimeBehavior, opts v1.CreateOptions) (*apiv1alpha1.RuntimeBehavior, error)
	Update(ctx context.Context, runtimeBehavior *apiv1alpha1.RuntimeBehavior, opts v1.UpdateOptions) (*apiv1alpha1.RuntimeBehavior, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, runtimeBehavior *apiv1alpha1.RuntimeBehavior, opts v1.UpdateOptions) (*apiv1alpha1.RuntimeBehavior, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.RuntimeBehavior, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.RuntimeBehaviorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.RuntimeBehavior, err error)
	RuntimeBehaviorExpansion
}

// runtimeBehaviors implements RuntimeBehaviorInterface
type runtimeBehaviors struct {
	*gentype.ClientWithList[*apiv1alpha1.RuntimeBehavior, *apiv1alpha1.RuntimeBehaviorList]
}

// newRuntimeBehaviors returns a RuntimeBehaviors
func newRuntimeBehaviors(c *RuntimeV1alpha1Client, namespace string) *runtimeBehaviors {
	return &runtimeBehaviors{
		gentype.NewClientWithList[*apiv1alpha1.RuntimeBehavior, *apiv1alpha1.RuntimeBehaviorList](
			"runtimebehaviors",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.RuntimeBehavior { return &apiv1alpha1.RuntimeBehavior{} },
			func() *apiv1alpha1.RuntimeBehaviorList { return &apiv1alpha1.RuntimeBehaviorList{} },
		),
	}
}
