// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package protofilter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type protoClassifierFlowKey struct {
	_       structs.HostLayout
	Saddr   [16]uint8
	Daddr   [16]uint8
	Sport   uint16
	Dport   uint16
	L4proto uint8
	Family  uint8
}

type protoClassifierFlowState struct {
	_        structs.HostLayout
	Proto    uint32
	Alpn     [16]int8
	Decision uint32
}

type protoClassifierProtoEventKey struct {
	_        structs.HostLayout
	Proto    uint32
	Alpn     [16]int8
	Decision uint32
}

type protoClassifierProtoKey struct {
	_     structs.HostLayout
	Proto uint32
	Alpn  [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	protoClassifierMapAllowedProtos = "allowed_protos"
	protoClassifierMapBannedProtos  = "banned_protos"
	protoClassifierMapFlags         = "flags"
	protoClassifierMapFlows         = "flows"
	protoClassifierMapProtoEvents   = "proto_events"
	protoClassifierProgProtoEgress  = "proto_egress"
)

// loadProtoClassifier returns the embedded CollectionSpec for protoClassifier.
func loadProtoClassifier() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProtoClassifierBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load protoClassifier: %w", err)
	}

	return spec, err
}

// loadProtoClassifierObjects loads protoClassifier and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*protoClassifierObjects
//	*protoClassifierPrograms
//	*protoClassifierMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProtoClassifierObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProtoClassifier()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// protoClassifierSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type protoClassifierSpecs struct {
	protoClassifierProgramSpecs
	protoClassifierMapSpecs
	protoClassifierVariableSpecs
}

// protoClassifierProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type protoClassifierProgramSpecs struct {
	ProtoEgress *ebpf.ProgramSpec `ebpf:"proto_egress"`
}

// protoClassifierMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type protoClassifierMapSpecs struct {
	AllowedProtos *ebpf.MapSpec `ebpf:"allowed_protos"`
	BannedProtos  *ebpf.MapSpec `ebpf:"banned_protos"`
	Flags         *ebpf.MapSpec `ebpf:"flags"`
	Flows         *ebpf.MapSpec `ebpf:"flows"`
	ProtoEvents   *ebpf.MapSpec `ebpf:"proto_events"`
}

// protoClassifierVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type protoClassifierVariableSpecs struct {
}

// protoClassifierObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProtoClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type protoClassifierObjects struct {
	protoClassifierPrograms
	protoClassifierMaps
	protoClassifierVariables
}

func (o *protoClassifierObjects) Close() error {
	return _ProtoClassifierClose(
		&o.protoClassifierPrograms,
		&o.protoClassifierMaps,
	)
}

// protoClassifierMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProtoClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type protoClassifierMaps struct {
	AllowedProtos *ebpf.Map `ebpf:"allowed_protos"`
	BannedProtos  *ebpf.Map `ebpf:"banned_protos"`
	Flags         *ebpf.Map `ebpf:"flags"`
	Flows         *ebpf.Map `ebpf:"flows"`
	ProtoEvents   *ebpf.Map `ebpf:"proto_events"`
}

func (m *protoClassifierMaps) Close() error {
	return _ProtoClassifierClose(
		m.AllowedProtos,
		m.BannedProtos,
		m.Flags,
		m.Flows,
		m.ProtoEvents,
	)
}

// protoClassifierVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProtoClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type protoClassifierVariables struct {
}

// protoClassifierPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProtoClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type protoClassifierPrograms struct {
	ProtoEgress *ebpf.Program `ebpf:"proto_egress"`
}

func (p *protoClassifierPrograms) Close() error {
	return _ProtoClassifierClose(
		p.ProtoEgress,
	)
}

func _ProtoClassifierClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed protoclassifier_bpfel.o
var _ProtoClassifierBytes []byte
