/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	kyvernoruntimeapiv1alpha1 "github.com/nirmata/kyverno-runtime/api/v1alpha1"
	versioned "github.com/nirmata/kyverno-runtime/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nirmata/kyverno-runtime/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/nirmata/kyverno-runtime/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RuntimeBehaviorInformer provides access to a shared informer and lister for
// RuntimeBehaviors.
type RuntimeBehaviorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.RuntimeBehaviorLister
}

type runtimeBehaviorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRuntimeBehaviorInformer constructs a new informer for RuntimeBehavior type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRuntimeBehaviorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRuntimeBehaviorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRuntimeBehaviorInformer constructs a new informer for RuntimeBehavior type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRuntimeBehaviorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().RuntimeBehaviors(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().RuntimeBehaviors(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().RuntimeBehaviors(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RuntimeV1alpha1().RuntimeBehaviors(namespace).Watch(ctx, options)
			},
		}, client),
		&kyvernoruntimeapiv1alpha1.RuntimeBehavior{},
		resyncPeriod,
		indexers,
	)
}

func (f *runtimeBehaviorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRuntimeBehaviorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *runtimeBehaviorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kyvernoruntimeapiv1alpha1.RuntimeBehavior{}, f.defaultInformer)
}

func (f *runtimeBehaviorInformer) Lister() apiv1alpha1.RuntimeBehaviorLister {
	return apiv1alpha1.NewRuntimeBehaviorLister(f.Informer().GetIndexer())
}
