//go:build !ignore_autogenerated

/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Behavior) DeepCopyInto(out *Behavior) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(BehaviorRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = new(BehaviorRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Behavior.
func (in *Behavior) DeepCopy() *Behavior {
	if in == nil {
		return nil
	}
	out := new(Behavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviorRule) DeepCopyInto(out *BehaviorRule) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviorRule.
func (in *BehaviorRule) DeepCopy() *BehaviorRule {
	if in == nil {
		return nil
	}
	out := new(BehaviorRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorFilter) DeepCopyInto(out *MonitorFilter) {
	*out = *in
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]MonitorFilterExpression, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorFilter.
func (in *MonitorFilter) DeepCopy() *MonitorFilter {
	if in == nil {
		return nil
	}
	out := new(MonitorFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorFilterExpression) DeepCopyInto(out *MonitorFilterExpression) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorFilterExpression.
func (in *MonitorFilterExpression) DeepCopy() *MonitorFilterExpression {
	if in == nil {
		return nil
	}
	out := new(MonitorFilterExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePolicyStatus) DeepCopyInto(out *NodePolicyStatus) {
	*out = *in
	if in.LastEvaluatedTime != nil {
		in, out := &in.LastEvaluatedTime, &out.LastEvaluatedTime
		*out = (*in).DeepCopy()
	}
	if in.EnforcementAvailable != nil {
		in, out := &in.EnforcementAvailable, &out.EnforcementAvailable
		*out = new(bool)
		**out = **in
	}
	if in.ObservationAvailable != nil {
		in, out := &in.ObservationAvailable, &out.ObservationAvailable
		*out = new(bool)
		**out = **in
	}
	if in.PodsMatched != nil {
		in, out := &in.PodsMatched, &out.PodsMatched
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePolicyStatus.
func (in *NodePolicyStatus) DeepCopy() *NodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBehavior) DeepCopyInto(out *PolicyBehavior) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Open != nil {
		in, out := &in.Open, &out.Open
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(Behavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBehavior.
func (in *PolicyBehavior) DeepCopy() *PolicyBehavior {
	if in == nil {
		return nil
	}
	out := new(PolicyBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePolicy) DeepCopyInto(out *RuntimePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePolicy.
func (in *RuntimePolicy) DeepCopy() *RuntimePolicy {
	if in == nil {
		return nil
	}
	out := new(RuntimePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePolicyList) DeepCopyInto(out *RuntimePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePolicyList.
func (in *RuntimePolicyList) DeepCopy() *RuntimePolicyList {
	if in == nil {
		return nil
	}
	out := new(RuntimePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePolicySpec) DeepCopyInto(out *RuntimePolicySpec) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EvaluationInterval != nil {
		in, out := &in.EvaluationInterval, &out.EvaluationInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]admissionregistrationv1.Variable, len(*in))
		copy(*out, *in)
	}
	if in.Behaviors != nil {
		in, out := &in.Behaviors, &out.Behaviors
		*out = make([]PolicyBehavior, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(RuntimePolicyMode)
		**out = **in
	}
	if in.MonitorFilter != nil {
		in, out := &in.MonitorFilter, &out.MonitorFilter
		*out = new(MonitorFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePolicySpec.
func (in *RuntimePolicySpec) DeepCopy() *RuntimePolicySpec {
	if in == nil {
		return nil
	}
	out := new(RuntimePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePolicyStatus) DeepCopyInto(out *RuntimePolicyStatus) {
	*out = *in
	if in.LastEvaluatedTime != nil {
		in, out := &in.LastEvaluatedTime, &out.LastEvaluatedTime
		*out = (*in).DeepCopy()
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodePolicyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePolicyStatus.
func (in *RuntimePolicyStatus) DeepCopy() *RuntimePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
