/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nirmata/kyverno-runtime/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AIInventoryLister helps list AIInventories.
// All objects returned here must be treated as read-only.
type AIInventoryLister interface {
	// List lists all AIInventories in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.AIInventory, err error)
	// Get retrieves the AIInventory from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.AIInventory, error)
	AIInventoryListerExpansion
}

// aIInventoryLister implements the AIInventoryLister interface.
type aIInventoryLister struct {
	listers.ResourceIndexer[*apiv1alpha1.AIInventory]
}

// NewAIInventoryLister returns a new AIInventoryLister.
func NewAIInventoryLister(indexer cache.Indexer) AIInventoryLister {
	return &aIInventoryLister{listers.New[*apiv1alpha1.AIInventory](indexer, apiv1alpha1.Resource("aiinventory"))}
}
