/*
Copyright The Kyverno Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/nirmata/kyverno-runtime/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RuntimeBehaviorLister helps list RuntimeBehaviors.
// All objects returned here must be treated as read-only.
type RuntimeBehaviorLister interface {
	// List lists all RuntimeBehaviors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RuntimeBehavior, err error)
	// RuntimeBehaviors returns an object that can list and get RuntimeBehaviors.
	RuntimeBehaviors(namespace string) RuntimeBehaviorNamespaceLister
	RuntimeBehaviorListerExpansion
}

// runtimeBehaviorLister implements the RuntimeBehaviorLister interface.
type runtimeBehaviorLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RuntimeBehavior]
}

// NewRuntimeBehaviorLister returns a new RuntimeBehaviorLister.
func NewRuntimeBehaviorLister(indexer cache.Indexer) RuntimeBehaviorLister {
	return &runtimeBehaviorLister{listers.New[*apiv1alpha1.RuntimeBehavior](indexer, apiv1alpha1.Resource("runtimebehavior"))}
}

// RuntimeBehaviors returns an object that can list and get RuntimeBehaviors.
func (s *runtimeBehaviorLister) RuntimeBehaviors(namespace string) RuntimeBehaviorNamespaceLister {
	return runtimeBehaviorNamespaceLister{listers.NewNamespaced[*apiv1alpha1.RuntimeBehavior](s.ResourceIndexer, namespace)}
}

// RuntimeBehaviorNamespaceLister helps list and get RuntimeBehaviors.
// All objects returned here must be treated as read-only.
type RuntimeBehaviorNamespaceLister interface {
	// List lists all RuntimeBehaviors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RuntimeBehavior, err error)
	// Get retrieves the RuntimeBehavior from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.RuntimeBehavior, error)
	RuntimeBehaviorNamespaceListerExpansion
}

// runtimeBehaviorNamespaceLister implements the RuntimeBehaviorNamespaceLister
// interface.
type runtimeBehaviorNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RuntimeBehavior]
}
