apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kyverno-runtime.fullname" . }}
  labels:
    {{- include "kyverno-runtime.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kyverno-runtime.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: daemon
  template:
    metadata:
      labels:
        {{- include "kyverno-runtime.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: daemon
        {{- with .Values.daemon.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.daemon.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kyverno-runtime.serviceAccountName" . }}
      hostPID: true
      containers:
      - name: daemon
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
          runAsUser: 0
        args:
        - daemon
        env:
        - name: HOST_ROOT
          value: /host
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: host-run
          mountPath: /run
        - name: host-var-run
          mountPath: /var/run
        - name: host-sys-fs-bpf
          mountPath: /sys/fs/bpf
        - name: host-sys-kernel-debug
          mountPath: /sys/kernel/debug
        - name: host-sys-kernel-tracing
          mountPath: /sys/kernel/tracing
        resources:
          {{- toYaml .Values.daemon.resources | nindent 10 }}
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: host-run
        hostPath:
          path: /run
          type: Directory
      - name: host-var-run
        hostPath:
          path: /var/run
          type: Directory
      - name: host-sys-fs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: host-sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
      - name: host-sys-kernel-tracing
        hostPath:
          path: /sys/kernel/tracing
          type: DirectoryOrCreate
      {{- with .Values.daemon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemon.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemon.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
