// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lsmDispatcherFileOpenEntry struct {
	_        structs.HostLayout
	DataType uint32
	Data     [128]int8
}

type lsmDispatcherFileOpenPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

type lsmDispatcherFileOpenPolicyCtx struct {
	_        structs.HostLayout
	ProgType uint8
	Reason   uint8
	Path     [128]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	lsmDispatcherFileOpenMapCtxMap             = "ctx_map"
	lsmDispatcherFileOpenMapExecPolicies       = "exec_policies"
	lsmDispatcherFileOpenMapExecProg           = "exec_prog"
	lsmDispatcherFileOpenMapInnerOpenEvents    = "inner_open_events"
	lsmDispatcherFileOpenMapInnerPolicyMap     = "inner_policy_map"
	lsmDispatcherFileOpenMapOpenEvents         = "open_events"
	lsmDispatcherFileOpenMapOpenPolicies       = "open_policies"
	lsmDispatcherFileOpenMapOpenProg           = "open_prog"
	lsmDispatcherFileOpenMapProgCount          = "prog_count"
	lsmDispatcherFileOpenMapStats              = "stats"
	lsmDispatcherFileOpenProgGenericLsmHandler = "generic_lsm_handler"
)

// loadLsmDispatcherFileOpen returns the embedded CollectionSpec for lsmDispatcherFileOpen.
func loadLsmDispatcherFileOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LsmDispatcherFileOpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lsmDispatcherFileOpen: %w", err)
	}

	return spec, err
}

// loadLsmDispatcherFileOpenObjects loads lsmDispatcherFileOpen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lsmDispatcherFileOpenObjects
//	*lsmDispatcherFileOpenPrograms
//	*lsmDispatcherFileOpenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLsmDispatcherFileOpenObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLsmDispatcherFileOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lsmDispatcherFileOpenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenSpecs struct {
	lsmDispatcherFileOpenProgramSpecs
	lsmDispatcherFileOpenMapSpecs
	lsmDispatcherFileOpenVariableSpecs
}

// lsmDispatcherFileOpenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenProgramSpecs struct {
	GenericLsmHandler *ebpf.ProgramSpec `ebpf:"generic_lsm_handler"`
}

// lsmDispatcherFileOpenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenMapSpecs struct {
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	ExecPolicies    *ebpf.MapSpec `ebpf:"exec_policies"`
	ExecProg        *ebpf.MapSpec `ebpf:"exec_prog"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	InnerPolicyMap  *ebpf.MapSpec `ebpf:"inner_policy_map"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenPolicies    *ebpf.MapSpec `ebpf:"open_policies"`
	OpenProg        *ebpf.MapSpec `ebpf:"open_prog"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// lsmDispatcherFileOpenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lsmDispatcherFileOpenVariableSpecs struct {
}

// lsmDispatcherFileOpenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenObjects struct {
	lsmDispatcherFileOpenPrograms
	lsmDispatcherFileOpenMaps
	lsmDispatcherFileOpenVariables
}

func (o *lsmDispatcherFileOpenObjects) Close() error {
	return _LsmDispatcherFileOpenClose(
		&o.lsmDispatcherFileOpenPrograms,
		&o.lsmDispatcherFileOpenMaps,
	)
}

// lsmDispatcherFileOpenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenMaps struct {
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	ExecPolicies    *ebpf.Map `ebpf:"exec_policies"`
	ExecProg        *ebpf.Map `ebpf:"exec_prog"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	InnerPolicyMap  *ebpf.Map `ebpf:"inner_policy_map"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenPolicies    *ebpf.Map `ebpf:"open_policies"`
	OpenProg        *ebpf.Map `ebpf:"open_prog"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *lsmDispatcherFileOpenMaps) Close() error {
	return _LsmDispatcherFileOpenClose(
		m.CtxMap,
		m.ExecPolicies,
		m.ExecProg,
		m.InnerOpenEvents,
		m.InnerPolicyMap,
		m.OpenEvents,
		m.OpenPolicies,
		m.OpenProg,
		m.ProgCount,
		m.Stats,
	)
}

// lsmDispatcherFileOpenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenVariables struct {
}

// lsmDispatcherFileOpenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLsmDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type lsmDispatcherFileOpenPrograms struct {
	GenericLsmHandler *ebpf.Program `ebpf:"generic_lsm_handler"`
}

func (p *lsmDispatcherFileOpenPrograms) Close() error {
	return _LsmDispatcherFileOpenClose(
		p.GenericLsmHandler,
	)
}

func _LsmDispatcherFileOpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lsmdispatcherfileopen_bpfel.o
var _LsmDispatcherFileOpenBytes []byte
