// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rawTpDispatcherExecCheckPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

type rawTpDispatcherExecCheckPolicyCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	ShouldPkill  uint8
	Path         [128]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	rawTpDispatcherExecCheckMapAllowed                   = "allowed"
	rawTpDispatcherExecCheckMapBanned                    = "banned"
	rawTpDispatcherExecCheckMapCgids                     = "cgids"
	rawTpDispatcherExecCheckMapCtxMap                    = "ctx_map"
	rawTpDispatcherExecCheckMapDefaultDeny               = "default_deny"
	rawTpDispatcherExecCheckMapExecProgs                 = "exec_progs"
	rawTpDispatcherExecCheckMapInnerOpenEvents           = "inner_open_events"
	rawTpDispatcherExecCheckMapOpenEvents                = "open_events"
	rawTpDispatcherExecCheckMapOpenProgs                 = "open_progs"
	rawTpDispatcherExecCheckMapProgCount                 = "prog_count"
	rawTpDispatcherExecCheckMapStats                     = "stats"
	rawTpDispatcherExecCheckProgGenericTracepointHandler = "generic_tracepoint_handler"
)

// loadRawTpDispatcherExecCheck returns the embedded CollectionSpec for rawTpDispatcherExecCheck.
func loadRawTpDispatcherExecCheck() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RawTpDispatcherExecCheckBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rawTpDispatcherExecCheck: %w", err)
	}

	return spec, err
}

// loadRawTpDispatcherExecCheckObjects loads rawTpDispatcherExecCheck and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rawTpDispatcherExecCheckObjects
//	*rawTpDispatcherExecCheckPrograms
//	*rawTpDispatcherExecCheckMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRawTpDispatcherExecCheckObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRawTpDispatcherExecCheck()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rawTpDispatcherExecCheckSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherExecCheckSpecs struct {
	rawTpDispatcherExecCheckProgramSpecs
	rawTpDispatcherExecCheckMapSpecs
	rawTpDispatcherExecCheckVariableSpecs
}

// rawTpDispatcherExecCheckProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherExecCheckProgramSpecs struct {
	GenericTracepointHandler *ebpf.ProgramSpec `ebpf:"generic_tracepoint_handler"`
}

// rawTpDispatcherExecCheckMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherExecCheckMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// rawTpDispatcherExecCheckVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherExecCheckVariableSpecs struct {
}

// rawTpDispatcherExecCheckObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherExecCheckObjects struct {
	rawTpDispatcherExecCheckPrograms
	rawTpDispatcherExecCheckMaps
	rawTpDispatcherExecCheckVariables
}

func (o *rawTpDispatcherExecCheckObjects) Close() error {
	return _RawTpDispatcherExecCheckClose(
		&o.rawTpDispatcherExecCheckPrograms,
		&o.rawTpDispatcherExecCheckMaps,
	)
}

// rawTpDispatcherExecCheckMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherExecCheckMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *rawTpDispatcherExecCheckMaps) Close() error {
	return _RawTpDispatcherExecCheckClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// rawTpDispatcherExecCheckVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherExecCheckVariables struct {
}

// rawTpDispatcherExecCheckPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherExecCheckObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherExecCheckPrograms struct {
	GenericTracepointHandler *ebpf.Program `ebpf:"generic_tracepoint_handler"`
}

func (p *rawTpDispatcherExecCheckPrograms) Close() error {
	return _RawTpDispatcherExecCheckClose(
		p.GenericTracepointHandler,
	)
}

func _RawTpDispatcherExecCheckClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rawtpdispatcherexeccheck_bpfel.o
var _RawTpDispatcherExecCheckBytes []byte
