// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rawTpDispatcherFileOpenLsmCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	ShouldPkill  uint8
	Path         [128]int8
}

type rawTpDispatcherFileOpenPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	rawTpDispatcherFileOpenMapAllowed                   = "allowed"
	rawTpDispatcherFileOpenMapBanned                    = "banned"
	rawTpDispatcherFileOpenMapCgids                     = "cgids"
	rawTpDispatcherFileOpenMapCtxMap                    = "ctx_map"
	rawTpDispatcherFileOpenMapDefaultDeny               = "default_deny"
	rawTpDispatcherFileOpenMapExecProgs                 = "exec_progs"
	rawTpDispatcherFileOpenMapInnerOpenEvents           = "inner_open_events"
	rawTpDispatcherFileOpenMapOpenEvents                = "open_events"
	rawTpDispatcherFileOpenMapOpenProgs                 = "open_progs"
	rawTpDispatcherFileOpenMapProgCount                 = "prog_count"
	rawTpDispatcherFileOpenMapStats                     = "stats"
	rawTpDispatcherFileOpenProgGenericTracepointHandler = "generic_tracepoint_handler"
)

// loadRawTpDispatcherFileOpen returns the embedded CollectionSpec for rawTpDispatcherFileOpen.
func loadRawTpDispatcherFileOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RawTpDispatcherFileOpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rawTpDispatcherFileOpen: %w", err)
	}

	return spec, err
}

// loadRawTpDispatcherFileOpenObjects loads rawTpDispatcherFileOpen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rawTpDispatcherFileOpenObjects
//	*rawTpDispatcherFileOpenPrograms
//	*rawTpDispatcherFileOpenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRawTpDispatcherFileOpenObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRawTpDispatcherFileOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rawTpDispatcherFileOpenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherFileOpenSpecs struct {
	rawTpDispatcherFileOpenProgramSpecs
	rawTpDispatcherFileOpenMapSpecs
	rawTpDispatcherFileOpenVariableSpecs
}

// rawTpDispatcherFileOpenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherFileOpenProgramSpecs struct {
	GenericTracepointHandler *ebpf.ProgramSpec `ebpf:"generic_tracepoint_handler"`
}

// rawTpDispatcherFileOpenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherFileOpenMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// rawTpDispatcherFileOpenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rawTpDispatcherFileOpenVariableSpecs struct {
}

// rawTpDispatcherFileOpenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherFileOpenObjects struct {
	rawTpDispatcherFileOpenPrograms
	rawTpDispatcherFileOpenMaps
	rawTpDispatcherFileOpenVariables
}

func (o *rawTpDispatcherFileOpenObjects) Close() error {
	return _RawTpDispatcherFileOpenClose(
		&o.rawTpDispatcherFileOpenPrograms,
		&o.rawTpDispatcherFileOpenMaps,
	)
}

// rawTpDispatcherFileOpenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherFileOpenMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *rawTpDispatcherFileOpenMaps) Close() error {
	return _RawTpDispatcherFileOpenClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// rawTpDispatcherFileOpenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherFileOpenVariables struct {
}

// rawTpDispatcherFileOpenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRawTpDispatcherFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type rawTpDispatcherFileOpenPrograms struct {
	GenericTracepointHandler *ebpf.Program `ebpf:"generic_tracepoint_handler"`
}

func (p *rawTpDispatcherFileOpenPrograms) Close() error {
	return _RawTpDispatcherFileOpenClose(
		p.GenericTracepointHandler,
	)
}

func _RawTpDispatcherFileOpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rawtpdispatcherfileopen_bpfel.o
var _RawTpDispatcherFileOpenBytes []byte
