// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type runtimePolicyLsmCtx struct {
	_            structs.HostLayout
	Deny         uint8
	NextProgIdx  uint8
	HaveExecuted uint8
	ProgType     uint8
	Reason       uint8
	ShouldPkill  uint8
	Path         [128]int8
}

type runtimePolicyPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	runtimePolicyMapAllowed                = "allowed"
	runtimePolicyMapBanned                 = "banned"
	runtimePolicyMapCgids                  = "cgids"
	runtimePolicyMapChainProgs             = "chain_progs"
	runtimePolicyMapCtxMap                 = "ctx_map"
	runtimePolicyMapDefaultDeny            = "default_deny"
	runtimePolicyMapExecProgs              = "exec_progs"
	runtimePolicyMapInnerOpenEvents        = "inner_open_events"
	runtimePolicyMapOpenEvents             = "open_events"
	runtimePolicyMapOpenProgs              = "open_progs"
	runtimePolicyMapProgCount              = "prog_count"
	runtimePolicyMapStats                  = "stats"
	runtimePolicyProgRuntimePolicyExecutor = "runtime_policy_executor"
)

// loadRuntimePolicy returns the embedded CollectionSpec for runtimePolicy.
func loadRuntimePolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RuntimePolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load runtimePolicy: %w", err)
	}

	return spec, err
}

// loadRuntimePolicyObjects loads runtimePolicy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*runtimePolicyObjects
//	*runtimePolicyPrograms
//	*runtimePolicyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRuntimePolicyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRuntimePolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// runtimePolicySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicySpecs struct {
	runtimePolicyProgramSpecs
	runtimePolicyMapSpecs
	runtimePolicyVariableSpecs
}

// runtimePolicyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyProgramSpecs struct {
	RuntimePolicyExecutor *ebpf.ProgramSpec `ebpf:"runtime_policy_executor"`
}

// runtimePolicyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyMapSpecs struct {
	Allowed         *ebpf.MapSpec `ebpf:"allowed"`
	Banned          *ebpf.MapSpec `ebpf:"banned"`
	Cgids           *ebpf.MapSpec `ebpf:"cgids"`
	ChainProgs      *ebpf.MapSpec `ebpf:"chain_progs"`
	CtxMap          *ebpf.MapSpec `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.MapSpec `ebpf:"default_deny"`
	ExecProgs       *ebpf.MapSpec `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.MapSpec `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.MapSpec `ebpf:"open_events"`
	OpenProgs       *ebpf.MapSpec `ebpf:"open_progs"`
	ProgCount       *ebpf.MapSpec `ebpf:"prog_count"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
}

// runtimePolicyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyVariableSpecs struct {
}

// runtimePolicyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyObjects struct {
	runtimePolicyPrograms
	runtimePolicyMaps
	runtimePolicyVariables
}

func (o *runtimePolicyObjects) Close() error {
	return _RuntimePolicyClose(
		&o.runtimePolicyPrograms,
		&o.runtimePolicyMaps,
	)
}

// runtimePolicyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyMaps struct {
	Allowed         *ebpf.Map `ebpf:"allowed"`
	Banned          *ebpf.Map `ebpf:"banned"`
	Cgids           *ebpf.Map `ebpf:"cgids"`
	ChainProgs      *ebpf.Map `ebpf:"chain_progs"`
	CtxMap          *ebpf.Map `ebpf:"ctx_map"`
	DefaultDeny     *ebpf.Map `ebpf:"default_deny"`
	ExecProgs       *ebpf.Map `ebpf:"exec_progs"`
	InnerOpenEvents *ebpf.Map `ebpf:"inner_open_events"`
	OpenEvents      *ebpf.Map `ebpf:"open_events"`
	OpenProgs       *ebpf.Map `ebpf:"open_progs"`
	ProgCount       *ebpf.Map `ebpf:"prog_count"`
	Stats           *ebpf.Map `ebpf:"stats"`
}

func (m *runtimePolicyMaps) Close() error {
	return _RuntimePolicyClose(
		m.Allowed,
		m.Banned,
		m.Cgids,
		m.ChainProgs,
		m.CtxMap,
		m.DefaultDeny,
		m.ExecProgs,
		m.InnerOpenEvents,
		m.OpenEvents,
		m.OpenProgs,
		m.ProgCount,
		m.Stats,
	)
}

// runtimePolicyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyVariables struct {
}

// runtimePolicyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyPrograms struct {
	RuntimePolicyExecutor *ebpf.Program `ebpf:"runtime_policy_executor"`
}

func (p *runtimePolicyPrograms) Close() error {
	return _RuntimePolicyClose(
		p.RuntimePolicyExecutor,
	)
}

func _RuntimePolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runtimepolicy_bpfel.o
var _RuntimePolicyBytes []byte
