// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package openexec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type runtimePolicyEntry struct {
	_        structs.HostLayout
	DataType uint32
	Data     [128]int8
}

type runtimePolicyPathEventKey struct {
	_        structs.HostLayout
	Path     [128]int8
	Decision uint32
}

type runtimePolicyPolicyCtx struct {
	_        structs.HostLayout
	ProgType uint8
	Reason   uint8
	Path     [128]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	runtimePolicyMapCtxMap                 = "ctx_map"
	runtimePolicyMapEventsMap              = "events_map"
	runtimePolicyMapExecPolicies           = "exec_policies"
	runtimePolicyMapExecProg               = "exec_prog"
	runtimePolicyMapInnerEvents            = "inner_events"
	runtimePolicyMapInnerPolicyMap         = "inner_policy_map"
	runtimePolicyMapOpenPolicies           = "open_policies"
	runtimePolicyMapOpenProg               = "open_prog"
	runtimePolicyMapProgCount              = "prog_count"
	runtimePolicyMapStats                  = "stats"
	runtimePolicyProgRuntimePolicyExecutor = "runtime_policy_executor"
)

// loadRuntimePolicy returns the embedded CollectionSpec for runtimePolicy.
func loadRuntimePolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RuntimePolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load runtimePolicy: %w", err)
	}

	return spec, err
}

// loadRuntimePolicyObjects loads runtimePolicy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*runtimePolicyObjects
//	*runtimePolicyPrograms
//	*runtimePolicyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRuntimePolicyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRuntimePolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// runtimePolicySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicySpecs struct {
	runtimePolicyProgramSpecs
	runtimePolicyMapSpecs
	runtimePolicyVariableSpecs
}

// runtimePolicyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyProgramSpecs struct {
	RuntimePolicyExecutor *ebpf.ProgramSpec `ebpf:"runtime_policy_executor"`
}

// runtimePolicyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyMapSpecs struct {
	CtxMap         *ebpf.MapSpec `ebpf:"ctx_map"`
	EventsMap      *ebpf.MapSpec `ebpf:"events_map"`
	ExecPolicies   *ebpf.MapSpec `ebpf:"exec_policies"`
	ExecProg       *ebpf.MapSpec `ebpf:"exec_prog"`
	InnerEvents    *ebpf.MapSpec `ebpf:"inner_events"`
	InnerPolicyMap *ebpf.MapSpec `ebpf:"inner_policy_map"`
	OpenPolicies   *ebpf.MapSpec `ebpf:"open_policies"`
	OpenProg       *ebpf.MapSpec `ebpf:"open_prog"`
	ProgCount      *ebpf.MapSpec `ebpf:"prog_count"`
	Stats          *ebpf.MapSpec `ebpf:"stats"`
}

// runtimePolicyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runtimePolicyVariableSpecs struct {
}

// runtimePolicyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyObjects struct {
	runtimePolicyPrograms
	runtimePolicyMaps
	runtimePolicyVariables
}

func (o *runtimePolicyObjects) Close() error {
	return _RuntimePolicyClose(
		&o.runtimePolicyPrograms,
		&o.runtimePolicyMaps,
	)
}

// runtimePolicyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyMaps struct {
	CtxMap         *ebpf.Map `ebpf:"ctx_map"`
	EventsMap      *ebpf.Map `ebpf:"events_map"`
	ExecPolicies   *ebpf.Map `ebpf:"exec_policies"`
	ExecProg       *ebpf.Map `ebpf:"exec_prog"`
	InnerEvents    *ebpf.Map `ebpf:"inner_events"`
	InnerPolicyMap *ebpf.Map `ebpf:"inner_policy_map"`
	OpenPolicies   *ebpf.Map `ebpf:"open_policies"`
	OpenProg       *ebpf.Map `ebpf:"open_prog"`
	ProgCount      *ebpf.Map `ebpf:"prog_count"`
	Stats          *ebpf.Map `ebpf:"stats"`
}

func (m *runtimePolicyMaps) Close() error {
	return _RuntimePolicyClose(
		m.CtxMap,
		m.EventsMap,
		m.ExecPolicies,
		m.ExecProg,
		m.InnerEvents,
		m.InnerPolicyMap,
		m.OpenPolicies,
		m.OpenProg,
		m.ProgCount,
		m.Stats,
	)
}

// runtimePolicyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyVariables struct {
}

// runtimePolicyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRuntimePolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type runtimePolicyPrograms struct {
	RuntimePolicyExecutor *ebpf.Program `ebpf:"runtime_policy_executor"`
}

func (p *runtimePolicyPrograms) Close() error {
	return _RuntimePolicyClose(
		p.RuntimePolicyExecutor,
	)
}

func _RuntimePolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runtimepolicy_bpfel.o
var _RuntimePolicyBytes []byte
