syntax = "proto3";

package learning;

import "google/protobuf/duration.proto";

option go_package = "github.com/nirmata/kyverno-runtime/pkg/proto/learning";

enum BehaviorKind {
  BEHAVIOR_NETWORK = 0;
  BEHAVIOR_OPEN = 1;
  BEHAVIOR_EXEC = 2;
};

service LearningService {
  rpc Start(StartRequest) returns (StartResponse);
  rpc Stop(StopRequest) returns (StopResponse);
  rpc Read(ReadRequest) returns (ReadResponse);
}

message StartRequest {
  string uid = 1;
  map<string, string> labels = 2;
  google.protobuf.Duration duration = 3;
}

message StartResponse {
}

message StopRequest {
  string uid = 1;
}

message StopResponse {
}

message ReadRequest {
  string uid = 1;
  repeated BehaviorKind behavior_kind = 2;
}

message ReadResponse {
  map<int32, int32> network = 1;
  map<string, int32> open = 2;
  map<string, int32> exec = 3;
}
