// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package exectrace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExecTrace returns the embedded CollectionSpec for execTrace.
func loadExecTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execTrace: %w", err)
	}

	return spec, err
}

// loadExecTraceObjects loads execTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execTraceObjects
//	*execTracePrograms
//	*execTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTraceSpecs struct {
	execTraceProgramSpecs
	execTraceMapSpecs
	execTraceVariableSpecs
}

// execTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTraceProgramSpecs struct {
	TraceExec *ebpf.ProgramSpec `ebpf:"trace_exec"`
}

// execTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTraceMapSpecs struct {
	Cgids  *ebpf.MapSpec `ebpf:"cgids"`
	Events *ebpf.MapSpec `ebpf:"events"`
	Stats  *ebpf.MapSpec `ebpf:"stats"`
}

// execTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTraceVariableSpecs struct {
}

// execTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTraceObjects struct {
	execTracePrograms
	execTraceMaps
	execTraceVariables
}

func (o *execTraceObjects) Close() error {
	return _ExecTraceClose(
		&o.execTracePrograms,
		&o.execTraceMaps,
	)
}

// execTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTraceMaps struct {
	Cgids  *ebpf.Map `ebpf:"cgids"`
	Events *ebpf.Map `ebpf:"events"`
	Stats  *ebpf.Map `ebpf:"stats"`
}

func (m *execTraceMaps) Close() error {
	return _ExecTraceClose(
		m.Cgids,
		m.Events,
		m.Stats,
	)
}

// execTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTraceVariables struct {
}

// execTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTracePrograms struct {
	TraceExec *ebpf.Program `ebpf:"trace_exec"`
}

func (p *execTracePrograms) Close() error {
	return _ExecTraceClose(
		p.TraceExec,
	)
}

func _ExecTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exectrace_bpfel.o
var _ExecTraceBytes []byte
