apiVersion: runtime.nirmata.io/v1alpha1
kind: RuntimePolicy
metadata:
  name: egress-to-cluster-service
spec:
  mode: enforce
  podSelector:
    matchLabels:
      app: gateway-client
  behaviors:
  - network:
      deny:
        values:
        - "*"
      allow:
        values:
        - kube-dns.kube-system.svc.cluster.local
        - egress-gateway.egress-gateway.svc.cluster.local
