// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/finding.proto

package finding

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindingService_Report_FullMethodName = "/finding.FindingService/Report"
)

// FindingServiceClient is the client API for FindingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FindingService receives the findings a kyverno-runtime daemon produces. The
// daemon is always the client: it opens the stream and never listens.
type FindingServiceClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Finding, Ack], error)
}

type findingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFindingServiceClient(cc grpc.ClientConnInterface) FindingServiceClient {
	return &findingServiceClient{cc}
}

func (c *findingServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Finding, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FindingService_ServiceDesc.Streams[0], FindingService_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Finding, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FindingService_ReportClient = grpc.ClientStreamingClient[Finding, Ack]

// FindingServiceServer is the server API for FindingService service.
// All implementations must embed UnimplementedFindingServiceServer
// for forward compatibility.
//
// FindingService receives the findings a kyverno-runtime daemon produces. The
// daemon is always the client: it opens the stream and never listens.
type FindingServiceServer interface {
	Report(grpc.ClientStreamingServer[Finding, Ack]) error
	mustEmbedUnimplementedFindingServiceServer()
}

// UnimplementedFindingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindingServiceServer struct{}

func (UnimplementedFindingServiceServer) Report(grpc.ClientStreamingServer[Finding, Ack]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedFindingServiceServer) mustEmbedUnimplementedFindingServiceServer() {}
func (UnimplementedFindingServiceServer) testEmbeddedByValue()                        {}

// UnsafeFindingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindingServiceServer will
// result in compilation errors.
type UnsafeFindingServiceServer interface {
	mustEmbedUnimplementedFindingServiceServer()
}

func RegisterFindingServiceServer(s grpc.ServiceRegistrar, srv FindingServiceServer) {
	// If the following call panics, it indicates UnimplementedFindingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindingService_ServiceDesc, srv)
}

func _FindingService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FindingServiceServer).Report(&grpc.GenericServerStream[Finding, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FindingService_ReportServer = grpc.ClientStreamingServer[Finding, Ack]

// FindingService_ServiceDesc is the grpc.ServiceDesc for FindingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finding.FindingService",
	HandlerType: (*FindingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _FindingService_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/finding.proto",
}
