// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/finding.proto

package finding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Finding mirrors the closed struct the daemon reports: typed scalar fields
// only, with no map, no body, and no free-form properties. Every string field
// is redacted before it is sent.
type Finding struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PolicyName string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyUid  string                 `protobuf:"bytes,2,opt,name=policy_uid,json=policyUid,proto3" json:"policy_uid,omitempty"`
	// behavior is one of "network", "open", "exec", "protocol", "dns".
	Behavior string `protobuf:"bytes,3,opt,name=behavior,proto3" json:"behavior,omitempty"`
	// target is the behavior's object: the destination, path, executed binary,
	// protocol[/alpn], or question name.
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// result is "fail" or "warn".
	Result string `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	// enforced is true when the kernel denied the operation, false for a
	// monitor-mode policy's "would have been denied" counterfactual.
	Enforced      bool                   `protobuf:"varint,6,opt,name=enforced,proto3" json:"enforced,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Pod           *Pod                   `protobuf:"bytes,8,opt,name=pod,proto3" json:"pod,omitempty"`
	Net           *Net                   `protobuf:"bytes,9,opt,name=net,proto3" json:"net,omitempty"`
	Dns           *Dns                   `protobuf:"bytes,10,opt,name=dns,proto3" json:"dns,omitempty"`
	Process       *Process               `protobuf:"bytes,11,opt,name=process,proto3" json:"process,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_proto_finding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{0}
}

func (x *Finding) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Finding) GetPolicyUid() string {
	if x != nil {
		return x.PolicyUid
	}
	return ""
}

func (x *Finding) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *Finding) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Finding) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Finding) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *Finding) GetNet() *Net {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *Finding) GetDns() *Dns {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *Finding) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *Finding) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Pod identifies the workload a finding is attributed to. Pod labels are
// absent by design: arbitrary user-controlled key/values are not sent.
type Pod struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Uid         string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Namespace   string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Container   string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	ContainerId string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// owner_kind and owner_name are best-effort correlation metadata read
	// verbatim from the pod's ownerReferences. Kubernetes validates that field
	// structurally, not behaviorally, so any principal able to create or patch a
	// pod can name any owner it likes. A receiver must not treat these as an
	// authenticated identity or use them as a security boundary.
	OwnerKind      string `protobuf:"bytes,6,opt,name=owner_kind,json=ownerKind,proto3" json:"owner_kind,omitempty"`
	OwnerName      string `protobuf:"bytes,7,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	NodeName       string `protobuf:"bytes,8,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ServiceAccount string `protobuf:"bytes,9,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_proto_finding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{1}
}

func (x *Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *Pod) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Pod) GetOwnerKind() string {
	if x != nil {
		return x.OwnerKind
	}
	return ""
}

func (x *Pod) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Pod) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

// Net summarizes the destination of a network finding.
type Net struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestIp        string                 `protobuf:"bytes,1,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestHost      string                 `protobuf:"bytes,2,opt,name=dest_host,json=destHost,proto3" json:"dest_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Net) Reset() {
	*x = Net{}
	mi := &file_proto_finding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Net) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net) ProtoMessage() {}

func (x *Net) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net.ProtoReflect.Descriptor instead.
func (*Net) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{2}
}

func (x *Net) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *Net) GetDestHost() string {
	if x != nil {
		return x.DestHost
	}
	return ""
}

// Dns summarizes the observed question of a dns finding.
type Dns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qname         string                 `protobuf:"bytes,1,opt,name=qname,proto3" json:"qname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dns) Reset() {
	*x = Dns{}
	mi := &file_proto_finding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dns) ProtoMessage() {}

func (x *Dns) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dns.ProtoReflect.Descriptor instead.
func (*Dns) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{3}
}

func (x *Dns) GetQname() string {
	if x != nil {
		return x.Qname
	}
	return ""
}

// Process summarizes the process of an exec/open finding.
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comm          string                 `protobuf:"bytes,1,opt,name=comm,proto3" json:"comm,omitempty"`
	Argv          string                 `protobuf:"bytes,2,opt,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_proto_finding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{4}
}

func (x *Process) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Process) GetArgv() string {
	if x != nil {
		return x.Argv
	}
	return ""
}

// Ack closes the stream, reporting how many findings the collector accepted.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_finding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_finding_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_proto_finding_proto protoreflect.FileDescriptor

const file_proto_finding_proto_rawDesc = "" +
	"\n" +
	"\x13proto/finding.proto\x12\afinding\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n" +
	"\aFinding\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12\x1d\n" +
	"\n" +
	"policy_uid\x18\x02 \x01(\tR\tpolicyUid\x12\x1a\n" +
	"\bbehavior\x18\x03 \x01(\tR\bbehavior\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x1a\n" +
	"\benforced\x18\x06 \x01(\bR\benforced\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1e\n" +
	"\x03pod\x18\b \x01(\v2\f.finding.PodR\x03pod\x12\x1e\n" +
	"\x03net\x18\t \x01(\v2\f.finding.NetR\x03net\x12\x1e\n" +
	"\x03dns\x18\n" +
	" \x01(\v2\f.finding.DnsR\x03dns\x12*\n" +
	"\aprocess\x18\v \x01(\v2\x10.finding.ProcessR\aprocess\x128\n" +
	"\ttimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8e\x02\n" +
	"\x03Pod\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"owner_kind\x18\x06 \x01(\tR\townerKind\x12\x1d\n" +
	"\n" +
	"owner_name\x18\a \x01(\tR\townerName\x12\x1b\n" +
	"\tnode_name\x18\b \x01(\tR\bnodeName\x12'\n" +
	"\x0fservice_account\x18\t \x01(\tR\x0eserviceAccount\";\n" +
	"\x03Net\x12\x17\n" +
	"\adest_ip\x18\x01 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_host\x18\x02 \x01(\tR\bdestHost\"\x1b\n" +
	"\x03Dns\x12\x14\n" +
	"\x05qname\x18\x01 \x01(\tR\x05qname\"1\n" +
	"\aProcess\x12\x12\n" +
	"\x04comm\x18\x01 \x01(\tR\x04comm\x12\x12\n" +
	"\x04argv\x18\x02 \x01(\tR\x04argv\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted2<\n" +
	"\x0eFindingService\x12*\n" +
	"\x06Report\x12\x10.finding.Finding\x1a\f.finding.Ack(\x01B.Z,github.com/nirmata/runtime/pkg/proto/findingb\x06proto3"

var (
	file_proto_finding_proto_rawDescOnce sync.Once
	file_proto_finding_proto_rawDescData []byte
)

func file_proto_finding_proto_rawDescGZIP() []byte {
	file_proto_finding_proto_rawDescOnce.Do(func() {
		file_proto_finding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finding_proto_rawDesc), len(file_proto_finding_proto_rawDesc)))
	})
	return file_proto_finding_proto_rawDescData
}

var file_proto_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_finding_proto_goTypes = []any{
	(*Finding)(nil),               // 0: finding.Finding
	(*Pod)(nil),                   // 1: finding.Pod
	(*Net)(nil),                   // 2: finding.Net
	(*Dns)(nil),                   // 3: finding.Dns
	(*Process)(nil),               // 4: finding.Process
	(*Ack)(nil),                   // 5: finding.Ack
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_finding_proto_depIdxs = []int32{
	1, // 0: finding.Finding.pod:type_name -> finding.Pod
	2, // 1: finding.Finding.net:type_name -> finding.Net
	3, // 2: finding.Finding.dns:type_name -> finding.Dns
	4, // 3: finding.Finding.process:type_name -> finding.Process
	6, // 4: finding.Finding.timestamp:type_name -> google.protobuf.Timestamp
	0, // 5: finding.FindingService.Report:input_type -> finding.Finding
	5, // 6: finding.FindingService.Report:output_type -> finding.Ack
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_finding_proto_init() }
func file_proto_finding_proto_init() {
	if File_proto_finding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finding_proto_rawDesc), len(file_proto_finding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finding_proto_goTypes,
		DependencyIndexes: file_proto_finding_proto_depIdxs,
		MessageInfos:      file_proto_finding_proto_msgTypes,
	}.Build()
	File_proto_finding_proto = out.File
	file_proto_finding_proto_goTypes = nil
	file_proto_finding_proto_depIdxs = nil
}
